### ISSUE TITLE
https://opensource.org/licenses/BSD-2-Clause is unavailable

### ISSUE THREAD

**Issue by DmitryFromDubna** [OpenSourceOrg/dotOrg#1]
Hello, 

https://opensource.org/licenses/BSD-2-Clause seems to be a well known link that has now become unavailable (returns HTTP 404 and "Oops! That page can’t be found." html). 

Apparently, the same license is available under https://opensource.org/license/bsd-license-php/

Will the original link be restored?

Thank you!

**Comment by smaffulli** [comment]
thanks for reporting this. Fixed now: https://opensource.org/license/bsd-2-clause/ (the server serves correctly the page if you use uppercase spelling)
