### ISSUE TITLE
OpenSource.org | Fix menu/header issues

### ISSUE THREAD

**Issue by toncijajic** [OpenSourceOrg/dotOrg#104]
While working on some other issues, we found several menu display issues across viewports which we want to resolve.

## Details

Please see @geoffguillain findings when sorting some other mobile menu issues:

> ### 1- Some breakpoints do not show the menu:
> ![image](https://github.com/OpenSourceOrg/dotOrg/assets/78659813/0dba2e3e-f074-4bf9-ba19-a08379ddfb69)
> 
> ### 2- the icons are not centered with the logo
> ![image](https://github.com/OpenSourceOrg/dotOrg/assets/78659813/7612ff83-d89b-49a4-a49f-5443c12e0ec8)
> 
> ### 3- There is no padding on the large and minimized header on mobile. I would suggest something more elegant like this: 
> ![image](https://github.com/OpenSourceOrg/dotOrg/assets/78659813/2ebc5b3b-b185-412b-9dbb-c6759fd542e9)
> 
> ### 4- The header disappears after scrolling on large devices
> Was investigated here: https://github.com/OpenSourceOrg/dotOrg/issues/92#issuecomment-2176160589

It should be all fairly self-explanatory, but please ping us if any additional info is needed.

**Comment by geoffguillain** [comment]
Hey @toncijajic 

I have fixed the issue mentioned above.
I had to revamp quite a lot of the header and nav styles as it seems that many styles were added over time and sometimes colliding with each other.

Demo: https://open-source-initiative-development.mystagingwebsite.com/

Please take a look at my proposed solution and let me know if you have any questions.

**Comment by toncijajic** [comment]
@geoffguillain neat, thank you!

Two quick questions, captured in this screencast: https://d.pr/v/jJ5oLl

- There's a bit of movement between the menu icon and menu label across the widths, are we able to fix that?
- The search icon isn't working (links to #), is that a develop-only thing (or is missing some class/identifier)?

**Comment by geoffguillain** [comment]
Hey @toncijajic 

> There's a bit of movement between the menu icon and menu label across the widths, are we able to fix that?
Thanks for your screencast it is helpful, there are some pixels between different screen sizes and the "slow" animation (ease) makes it obvious when resizing. It is pretty uncommon that people will see this movement as it is happening on small screens and people won't resize their mobile screens but I will remove/fix it! ;)

> The search icon isn't working (links to #), is that a develop-only thing (or is missing some class/identifier)?

The link on the search icon is triggering Jetpack Search but it is not activated on the develop server. I have not touched this part of the code and the link is set up correctly and should work as expected on prod.

**Comment by toncijajic** [comment]
@geoffguillain got it!

Feel free to deploy when ready!

**Comment by geoffguillain** [comment]
Hey @toncijajic 

I have changed the units on the menu button from em to px so the size doesn't change when you resize.

I have then pushed everything to production 
https://opensource.org/

Please take a look at my proposed solution and let me know if you have any questions.

**Comment by toncijajic** [comment]
@geoffguillain thanks!

Comparing the production site to the staging, the menu doesn't seem to stick to the top.
Could you check if anything went wrong?

**Comment by geoffguillain** [comment]
Hey @toncijajic 

Thanks for catching this!
I have found the culprit, there was some legacy CSS in the site site customizer colliding with the new styles.

The header is sticky now on production.

**Comment by toncijajic** [comment]
@geoffguillain looks great!

Closing.
