### ISSUE TITLE
incorrect certificate for www.opensource.org 

### ISSUE THREAD

**Issue by raboof** [OpenSourceOrg/dotOrg#105]
### Description

links like https://www.opensource.org/licenses/LGPL-2.1 redirect to https://opensource.org/licenses/LGPL-2.1 . This redirect is intact, but www.opensource.org is no longer served with a certificate for www.opensource.org (it only has `CN=*.pressable.com`)

### Steps to reproduce

Visit https://www.opensource.org/licenses/LGPL-2.1

### What you expected to happen

A redirect to https://opensource.org/licenses/LGPL-2.1

### What actually happened

A certificate error

**Comment by raboof** [comment]
seems to work again!

**Comment by nickvidal** [comment]
Thanks @raboof
