### ISSUE TITLE
GPL-2.0 Stewardship

### ISSUE THREAD

**Issue by leoheitmannruiz** [OpenSourceOrg/dotOrg#142]
Not sure if this belongs here, but I noticed that at https://opensource.org/blog/steward/free-software-foundation the GPL-2.0 isn't listed. 

Is this intentional?

**Comment by ajolo2ky** [comment]
Hi @leoheitmannruiz thanks for raising this issue (and for your ping over email :)), I've updated the license steward in both.

If you happen to run into any other issues like this, please let me know!
Thanks,
