### ISSUE TITLE
Create a wider page template

### ISSUE THREAD

**Issue by moyvincent** [OpenSourceOrg/dotOrg#145]
### Description
Our partner has reached out to help create a wider page template for the content area similar to what is on https://opensource.org/ai/endorsements.
![image](https://github.com/user-attachments/assets/14d996a6-5fa6-46b0-a110-180f1028d4d3)

Changes to the new page template can be made on the staging site for the partner to review first before moving to production.

**Comment by xpurichan** [comment]
I have implemented the following CSS to the dev site for review:

```
/* TEMP - See GH OpenSourceOrg/dotOrg/issues/145 */ 
.page-id-22485 .content.has_no_sidebar .content--page article:not(.archive) {
    max-width: 1084px !important;
}
```

Once we have confirmation that width and outcome is correct, then we can base our new "No Page Header - wide width" template on it.

**Comment by ajolo2ky** [comment]
This is working as expected. Thank you!
