### ISSUE TITLE
All paragraphs are small

### ISSUE THREAD

**Issue by nickvidal** [OpenSourceOrg/dotOrg#16]
### Description

We noticed recently that all paragraphs are really small. We found this CSS to be at fault (common.min.css):

.wp-die-message, p {
    font-size: 13px;

Where it should be:

.wp-die-message p {
    font-size: 13px;

No comma before "p". That extra comma is affecting all paragraphs.

Would you be able to help us please?

**Comment by Darruiz** [comment]
CSS code snippet.
Description of the issue.
Suggested CSS correction.
Request for assistance.
Steps to reproduce (if applicable).
Expected outcome.
Actual outcome.

**Comment by nickvidal** [comment]
Hi Darruiz,

I had to add a custom CSS to override the 13px font size for paragraphs defined on `common.min.css`

Please see screenshot attached.

![Screenshot from 2023-09-13 10-33-14](https://github.com/OpenSourceOrg/dotOrg/assets/7810941/a4349971-7f85-487c-b667-1ea04e55260d)

Thanks
