### ISSUE TITLE
Template for webinar video pages

### ISSUE THREAD

**Issue by deke207** [OpenSourceOrg/dotOrg#19]
### Description

The partner would like a template that does not render a featured image on the post frontend. This template would be used for their webinar post. 

Example post: https://href.li/?https://github.com/OpenSourceOrg/dotOrg/

### Additional context

>When we set a featured image, that image appears in the header of the default template. We would like for the featured image to show up only when we share it over social media, and leave the header intact, displaying only the title. Would that be possible please?

>We are looking to use this template specifically on the webinar video recording pages.

**Comment by bernattorras** [comment]
That should be easy to achieve @deke207, but I think there's an issue with the example URL that you shared, as it is pointing to the repo instead. 

Could you please provide the right example URL so we can confirm the kind of posts that should be updated? This way we'll be able to keep the same layout and styling in the new template.

Thanks!

**Comment by deke207** [comment]
@bernattorras - Sorry about that!
Example post: https://opensource.org/wp-admin/post.php?post=10071&action=edit

**Comment by bernattorras** [comment]
Thanks @deke207! 

I've started creating a new template for this kind of page, but realized that there's already a template named "**No Page Header**" that seems to be the same as the **Default page template** but without the featured header image. I've compared both templates and that's the only difference I see. Can't they just use this template? 

I've also checked it and when using this template with a featured image, this image (despite not being shown anywhere) is the one populated in the `og:image` meta tag, the one that displays the page image when sharing the page in social media. 

I've created this page in the staging site as an example so you can check it: 
https://open-source-initiative-development.mystagingwebsite.com/wp-admin/post.php?post=9719&action=edit

Can you please take a look at it and confirm if that will be enough to fit the partner's needs?

Thanks!

**Comment by deke207** [comment]
> but realized that there's already a template named "No Page Header" that seems to be the same as the Default page template but without the featured header image.

Oh, really? I suppose that template will work @bernattorras. Thank you. 🙇🏽

**Comment by nickvidal** [comment]
We would still want to see the title in the header. Would it be possible to create a template like this please?

**Comment by bernattorras** [comment]
>We would still want to see the title in the header. 

Could you please clarify what you're exactly referring to? 

As far as I see it, the title is rendered in the `No page header` template as well as with the default one. 

Here's a picture of the default template:

![image](https://github.com/OpenSourceOrg/dotOrg/assets/1201868/d46a9361-1de4-454a-8ab4-a050a1ce17da)

And here's one of the same page using the `No page header` template:

![image](https://github.com/OpenSourceOrg/dotOrg/assets/1201868/204c6de8-dd44-4ac7-b81c-feeb669d9890)

@nickvidal Could you please confirm if this is the same title you're referring to? If you're referring to a different one, please provide us an example (URL or screenshot) if possible to make sure we update the template with the proper format. 

Thanks!

**Comment by nickvidal** [comment]
That screenshot that you have attached displays the first paragraph, but no title.

**Comment by bernattorras** [comment]
Thanks for the clarification @nickvidal! I wrongly assumed that you were referring to that element! 

I've created the new `No Header with Title` template, which is a clone of the `No Page Header` but with an <h1> heading that renders the page title before the rest of the content. 

Here you can see this template in action: 

https://open-source-initiative-development.mystagingwebsite.com/copyright-right-answer-for-open-source-code-wrong-answer-for-open-source-ai/

Let me know if everything is ok now and if you want us to push these changes into production!

**Comment by nickvidal** [comment]
That's great @bernattorras. Thank you!

**Comment by bernattorras** [comment]
I've pushed these changes into production. Please feel free to reopen the issue if any other adjustments need to be made to the template. :)
