### ISSUE TITLE
PHP License 3.01 should not be tagged as "superseded"

### ISSUE THREAD

**Issue by ramsey** [OpenSourceOrg/dotOrg#2]
The new website looks great! Great work to all!

The page for PHP License 3.01 shows a pill-shaped label indicating it is superseded. This is not the case. Please remove the "superseded" tag.

For historical reference, on 21 Jan 2023, the alphabetical list of licenses did not indicate PHP License 3.01 was superseded: https://web.archive.org/web/20230121140616/https://opensource.org/licenses/alphabetical

Also, on 28 Jan 2023, the page for PHP License 3.01 did not indicate it was superseded: https://web.archive.org/web/20230128035956/https://opensource.org/licenses/PHP-3.01

See https://opensource.org/license/php-3-01/

<img width="939" alt="Screenshot 2023-02-14 at 17 11 43" src="https://user-images.githubusercontent.com/42941/218883991-cddbc815-385c-46dc-a961-f6ade8b328ef.png">

Also on https://opensource.org/licenses/

<img width="939" alt="Screenshot 2023-02-14 at 17 13 13" src="https://user-images.githubusercontent.com/42941/218884246-1b0c7ea8-3e20-40f3-ba56-12b3a3a2acd1.png">

**Comment by smaffulli** [comment]
Thank you for the clear report! This has been fixed now.
