### ISSUE TITLE
Investigate VideoPress cookies.

### ISSUE THREAD

**Issue by ErikSolveson** [OpenSourceOrg/dotOrg#20]
### Description

We would like to investigate:
- Which cookies are collected specifically by VideoPress
- Can we disable those cookies without impacting performance? 

Thank you,

### Additional context

We may want to start using VideoPress to take advantage of the CDN.

**Comment by bernattorras** [comment]
@ErikSolveson I've checked the Jetpack cookies [here](https://jetpack.com/support/cookies/) and I was unable to find any references to any VideoPress cookies, so I've [asked team Greenhouse directly in Slack](https://a8c.slack.com/archives/C9W0QF6KA/p1697715953033619).

They confirmed that VideoPress isn't storing any cookies, as the only ones that were used to remember the video player preferences were removed years ago to use local storage instead (more details in the Slack thread).  

So, this should solve any concerns about the tracking of VideoPress and the possible impact of blocking its -nonexistent- cookies. 

Please let me know if anything else needs to be clarified!

**Comment by klasharr** [comment]
The partner was happy with this info. Closing and thanks.
