### ISSUE TITLE
OpenSource.org | Add footer credits

### ISSUE THREAD

**Issue by toncijajic** [OpenSourceOrg/dotOrg#21]
We need to add a credits segment to the site's footer above the colophon WordPress information.

## Details

- The credits are quoted below
- We need to add them to the gray area above the "[Proudly powered by WordPress.](https://wordpress.com/wp/?partner_domain=opensource.org&utm_source=Automattic&utm_medium=colophon&utm_campaign=Concierge%20Referral&utm_term=opensource.org) [Hosted by Pressable.](https://pressable.com/?utm_source=Automattic&utm_medium=rpc&utm_campaign=Concierge%20Referral&utm_term=concierge)" colophon credits (https://d.pr/i/Uhz7J4)

> The content on this website, of which Opensource.org is the author, is licensed under a [Creative Commons Attribution 4.0 International License](https://web.archive.org/web/20230202005829/https://creativecommons.org/licenses/by/4.0/).
> Opensource.org is not the author of any of the licenses reproduced on this site. Questions about the copyright in a license should be directed to the license steward.

**Comment by bernattorras** [comment]
@toncijajic I've checked it and I see that for some reason the footer has a [hardcoded style att](https://github.com/OpenSourceOrg/dotOrg/blob/main/themes/osi/footer.php#L35) that sets its max-width of 480px.

![image](https://github.com/a8cteam51/team51-dev-requests/assets/1201868/17b3a092-0455-4d71-8725-27058300aaf3)

Could you clarify if this was done on purpose and if we still want to keep this max-width? Or can we get rid of it to give the footer the same width as the rest of the content?

**Comment by toncijajic** [comment]
> Could you clarify if this was done on purpose and if we still want to keep this max-width? Or can we get rid of it to give the footer the same width as the rest of the content?

@bernattorras not sure, I wasn't handling the initial page launch.

Can we trace the code back to who made it and why?

**Comment by bernattorras** [comment]
>Can we trace the code back to who made it and why?

This is the commit (from the previous repository) where this `max-width` harcoded style was added, but there aren't many details about the change, appart from "moving mega footer to its own feature branch"... 

https://github.com/a8cteam51/open-source-initiative/commit/fb06366a5a5313c2850c09c13ff7ea28801a3296

Imo, I don't see any particular reason to keep this limitation, as the only item in that area was the footer credits, and its content was smaller than this restriction (this is probably why the width restriction wasn't identified earlier).

**Comment by mdrovdahl** [comment]
@bernattorras thanks, go ahead and remove the limitation please.

**Comment by bernattorras** [comment]
I've added a new sidebar named "Footer - Above credits" to render that text (customizable from Appearance>Widgets) in the footer. I've also removed that max-width limitation.

You can see the changes here: https://open-source-initiative-development.mystagingwebsite.com/

@mdrovdahl @toncijajic  Let me know if I can push them into production.

**Comment by bryanwmiller** [comment]
@bernattorras - It looks good to me! Feel free to push it to production, and just let me know when it is done so I can inform the partner.

**Comment by bernattorras** [comment]
Done! 

Feel free to reopen the issue if anything else is needed!
