### ISSUE TITLE
Requirements analysis and tasks creation

### ISSUE THREAD

**Issue by klasharr** [OpenSourceOrg/dotOrg#27]
- [x] Content, functionality and plugin analysis - determine content, plugins, and settings to be migrated
- [x] Set up individual tasks and prioritise

Assignee @klasharr

**Comment by smaffulli** [comment]
from the functionality perspective, the plugins we need are Nelio Content (for calendar and social media publishing) and ActivityPub. 
On the current blog we also use the Indieweb plugins to aggregate the comments from the fediverse back into the site, as comments, likes and reposts but we're not married to those functions. 
Contact Form 7, CF7 CiviCRM integration, Flamingo are used to collect email addresses for the newsletter.
Other plugins are cosmetic ones, those can be discussed.

**Comment by bryanwmiller** [comment]
>On the current blog we also use the Indieweb plugins to aggregate the comments from the fediverse back into the site, as comments, likes and reposts but we're not married to those functions.

@smaffulli - Would you mind explaining this part a little more? Are you saying that you are okay with using a different plugin for this functionality, or are you okay not adding this functionality to the new blog/news posts?
