### ISSUE TITLE
Post Migration

### ISSUE THREAD

**Issue by bryanwmiller** [OpenSourceOrg/dotOrg#28]
- [x] On https://opensource.org/ delete the old events that are currently in ‘posts’
- [x] Migrate post entries over from https://blog.opensource.org/ ->  https://opensource.org/
- [x] For the migration, set up redirects in the old blog sub-site.

**Comment by klasharr** [comment]
Just noting that on a posts import to the development env, we saw some issues with the Featured Images not fully coming over.

**Comment by jessLundie** [comment]
> Just noting that on a posts import to the development env, we saw some issues with the Featured Images not fully coming over.

@klasharr - I've been looking at the development environment this morning and have a quick question. Does this mean you've already done these two steps on the development environment? Are the posts I'm seeing there an import as of the beginning of December?

> On https://opensource.org/ delete the old events that are currently in ‘posts’
> Migrate post entries over from https://blog.opensource.org/ -> https://opensource.org/

**Comment by NickGreen** [comment]
> we saw some issues with the Featured Images not fully coming over.

@klasharr Can you clarify this? What issues did you encounter exactly? Any error logs or more specifics here?

**Comment by klasharr** [comment]
> Can you clarify this? What issues did you encounter exactly? Any error logs or more specifics here?

Response

> We ran an export through WP Admin from the blog(dot) and then used the Importer through WP Admin and the WP CLI on the new site. Both worked without throwing any error messages, but there was an issue with the featured image. Here for post 4019.

Source site post:

![Screenshot 2024-01-19 at 08 49 53](https://github.com/OpenSourceOrg/dotOrg/assets/5604969/e83481b5-795a-469d-becf-77016b4c8fb3)

Dev site after import:

![Screenshot 2024-01-19 at 08 49 32](https://github.com/OpenSourceOrg/dotOrg/assets/5604969/aaa7b595-d34d-4e64-a3fd-7431ca249b2a)

**Comment by klasharr** [comment]
blog.opensource.org was migrated to opensource.org/blog on 2024-02-22.
