### ISSUE TITLE
Plugin Migration

### ISSUE THREAD

**Issue by bryanwmiller** [OpenSourceOrg/dotOrg#29]
- [x] Migrate over Nelio Content
- [x] Migrate over [Activity Pub](https://blog.opensource.org/wp-admin/options-general.php?page=activitypub) Content
- [x] Migrate over the Newsletter signup form - Contact Form 7, CF7 CiviCRM, Flamingo
- [x] Migrate over Indieweb or research alternatives (dependent upon the answer to [this question](https://github.com/OpenSourceOrg/dotOrg/issues/27#issuecomment-1841210409))

**Comment by klasharr** [comment]
blog.opensource.org was migrated to opensource.org/blog on 2024-02-22.
