### ISSUE TITLE
Strange URL redirections

### ISSUE THREAD

**Issue by ramsey** [OpenSourceOrg/dotOrg#3]
Some of the old license URLs redirect to pages I do not expect. Since many open source projects link directly to the license pages on the OSI website, these URLs should either not change or should redirect properly to the expected licenses.

| License | Old URL | Redirects to |
| ------- | ------- | ------------ |
| AGPL-3.0 | https://opensource.org/licenses/AGPL-3.0 | `404` |
| Apache-2.0 | https://opensource.org/licenses/Apache-2.0 | `404` |
| BSD-1-Clause | https://opensource.org/licenses/BSD-1-Clause | https://opensource.org/license/bsd-1-clause-2/ (content is correct, but URL seems strange) |
| BSD-2-Clause | https://opensource.org/licenses/BSD-2-Clause | `404` (reported in #1) |
| MIT | https://opensource.org/licenses/MIT | https://opensource.org/license/mit-0/ |
| PHP-3.0 | https://opensource.org/licenses/PHP-3.0 | https://opensource.org/license/php-3-01/ (this is not the same license) |

And, oddly, this new URL: <https://opensource.org/license/mit/> \
Redirects to: <https://opensource.org/license/mit-license-php/>

I only did a spot-check of the licenses listed here, so this may not be representative of all problems with license URLs: <https://web.archive.org/web/20230121140616/https://opensource.org/licenses/alphabetical>

**Comment by smaffulli** [comment]
https://opensource.org/license/bsd-1-clause/ fixed
https://opensource.org/licenses/BSD-2-Clause fixed

WordPress doesn't let me add a `.` dot in the URL, it's transforming it into a `-` so this URL is not working at the moment ... filing an issue with the WP team.
https://opensource.org/license/php-3.0/ 
https://opensource.org/license/agpl-v3/ 
https://opensource.org/license/apache2-0/ 
https://opensource.org/licenses/PHP-3.0

As soon as the website stabilizes a bit, we'll issue a more visible call for volunteers to sift through the list of licenses and correct the pages... we discovered a lot of inconsistencies as we migrated them and what you discovered is the what we missed in our checks.

**Comment by ramsey** [comment]
It seems like some of these redirections might be better (more easily) handled in the web server configuration (i.e., `.htaccess`, etc.), rather than in WordPress itself.

**Comment by DmitryFromDubna** [comment]
Hello, https://opensource.org/licenses/bsd-license.php was available just recently, but returns 404 now. Thank you.

**Comment by smaffulli** [comment]
the redirects are in place now, all the url work.

@DmitryFromDubna the URL you quoted was a mistake
