### ISSUE TITLE
Create Blog Archive Page

### ISSUE THREAD

**Issue by bryanwmiller** [OpenSourceOrg/dotOrg#30]
We want to recreate the Blog Archive from https://blog.opensource.org/ to a new page on the https://opensource.org/ site, using the https://opensource.org/news url. 

- [x] Set up an archive page for the posts called News, /news. This will be linked from the navigation bar
- [ ] Port over the sidebar and other elements like the featured post on the top page from[ blog.opensource.org](http://blog.opensource.org/)
- [x] Use the fonts and colors from https://opensource.org/.
- [x] The single post template from the new site works well for the new blog, but we may need to update the comments section (dependent upon the answer to [this question](https://github.com/OpenSourceOrg/dotOrg/issues/27#issuecomment-1841210409)).

**Comment by jessLundie** [comment]
**Working List of Additional Steps Related to This Issue**

* In Redirection plugin, disable, remove or handle as needed all `/news` -> `blog.` redirects that exist - this includes a number of RSS feed and xml-related redirects
* Reassign the menu item - affected menus: Primary Menu

**Comment by NickGreen** [comment]
Working branch for theme updates is here: https://github.com/OpenSourceOrg/dotOrg/tree/update/blog-import

**Comment by klasharr** [comment]
blog.opensource.org was migrated to opensource.org/blog on 2024-02-22.
