### ISSUE TITLE
SugarCalendar - Events overlapping

### ISSUE THREAD

**Issue by nickvidal** [OpenSourceOrg/dotOrg#31]
### Description

Events listed on the Events page overlap.

![image](https://github.com/OpenSourceOrg/dotOrg/assets/7810941/38d4dc71-0cab-4b68-8b7a-71631be787a2)

**Comment by ahegyes** [comment]
Hi @nickvidal! A fix for this has been implemented and merged in PR #44 for the staging site. 

Before:
![image](https://github.com/OpenSourceOrg/dotOrg/assets/36231502/233cd359-fa66-4c91-bb5e-57e541ac913e)

After:
![image](https://github.com/OpenSourceOrg/dotOrg/assets/36231502/169144a4-3993-4244-a915-121b1bf53bc9)


If you approve this change, we can push it to the live site by merging PR #45 😃

**Comment by nickvidal** [comment]
Thanks @ahegyes , looks great!

**Comment by ahegyes** [comment]
Thanks for the quick reply! PR #45 is now deployed 😄
