### ISSUE TITLE
SugarCalendar - ticket sales not working

### ISSUE THREAD

**Issue by ajolo2ky** [OpenSourceOrg/dotOrg#33]
### Description

Hi team, we are facing an issue with tickets sales. Hitting purchase hangs forever and tickets are not being sold (they are free)

### Steps to reproduce

Go to https://opensource.org/events/open-source-ai-definition-town-hall-4/
Click on Get a Ticket
Fill in the form and submit

### What you expected to happen

Finalize the purchase process

### What actually happened

This is the raw data sent: 'action=sc_et_stripe_create_payment_intent&email=ajolo%40opensource.org&name=Ariel+Jolo&event_id=47&quantity=1'

And this is the response (200 ok):
{"success":false,"data":{"sandbox":false}}

**Comment by ErikSolveson** [comment]
Upon hitting submit I'm seeing an issue with the Get request from the form.
<img width="710" alt="Screenshot 2024-01-08 at 1 47 38 PM" src="https://github.com/OpenSourceOrg/dotOrg/assets/25552931/84840597-a3b3-4439-a160-0668f75489b5">

**Comment by jonesch** [comment]
@ajolo2ky - when logged in to the site, it looks like Stripe has been disconnected. Or maybe it was not set up initially?

`wp-admin/admin.php?page=sc-settings&section=tickets&subsection=emails`.

Even though the tickets are free, our investigation is pointing us back to SugarCalendar requiring a connection to Stripe regardless of a ticket's price. 

From here, we can try either:
- Reach out to the [Suppor Team at SugarCalendar](https://sugarcalendar.com/support/) and ask if a $0 ticket requires a Stripe Connection?
- Connecting to a Stripe account

**Comment by nickpagz** [comment]
Hi @ajolo2ky 

It looks like the Stripe connection is still showing as "Disconnected". Is it possible to setup the connection so we can test if this is what is causing the issue?

Thanks!

**Comment by toncijajic** [comment]
@nickpagz forwarding a reply from @smaffulli (we got via email):

> working on it... our stripe account is brand new and nobody outside of accounting has access to it.

**Comment by smaffulli** [comment]
Stripe cannot be connected because there is a bug with Sugar Calendar. I
have notified the developers of Sugar. I have also asked WP Concierge for
advice on how to proceed. We can close this ticket for now.

**Comment by nickpagz** [comment]
Closing per request. We can re-open if required.
