### ISSUE TITLE
SugarCalendar - title gets displayed twice

### ISSUE THREAD

**Issue by ajolo2ky** [OpenSourceOrg/dotOrg#35]
### Description

<img width="1291" alt="image" src="https://github.com/OpenSourceOrg/dotOrg/assets/6595356/b54d975c-2aee-4579-a89e-c3e5de69f7a9">

### What you expected to happen

The title should be displayed only once

### What actually happened

It's displayed twice

**Comment by jonesch** [comment]
The SugarCalendar template file is pulling in both titles, so we added some CSS to hide the first title. 
<img width="1485" alt="image" src="https://github.com/OpenSourceOrg/dotOrg/assets/1905918/41264d24-ab04-46df-aab3-b3f57a2d091b">

@ajolo2ky - have a look and let us know if that's more in line with what you were thinking. Thanks!!

**Comment by smaffulli** [comment]
why not fix the template so that the code doesn't show two h1 elements?

**Comment by jonesch** [comment]
> why not fix the template so that the code doesn't show two h1 elements?
Good question. At first glance yesterday, I thought the Page Titles were part of the plugin. And if we were to edit the plugin, our edits would eventually get overwritten when the plugin updates itself.

After looking a bit deeper, I see the Page Titles on these event pages are handled by the template files. Specifically this line:
https://github.com/OpenSourceOrg/dotOrg/blob/main/themes/osi/template-parts/header-featured-image.php#L30

I created a Fork, and then opened a PR to merge the update back here.
@ajolo2ky or @smaffulli, not sure if either of you can merge the PR I created -  https://github.com/OpenSourceOrg/dotOrg/pull/38

**Comment by nickpagz** [comment]
I merged #38 as the code was already added on the server. Closing.
