### ISSUE TITLE
SugarCalendar - Free ticket displays weird characters

### ISSUE THREAD

**Issue by smaffulli** [OpenSourceOrg/dotOrg#36]
### Description

When an event is free, there are multiple UI issues. The biggest one is the price with extra characters. But also, the event is free so the labels should not say `$0` but "Free". Also, ideally the button should not say "Get a ticket" but rather simply "Register"

![image](https://github.com/OpenSourceOrg/dotOrg/assets/1348736/03cbc23a-4ac3-432a-9cbd-170af9eae40e)

I'm quite sure we addressed this issue already but I can't find the exact place... Maybe you can make more sense from the list of commits: https://github.com/a8cteam51/open-source-initiative/issues/191

### Steps to reproduce

Go to https://opensource.org/events/open-source-ai-definition-town-hall-4/
Check the registration box
Notice how the price is displayed

### What you expected to happen

Instead of a reference to price, ideally the event should be clearly marked as a free event.

### What actually happened

The text shows

` -$-0 Per Ticket `

with extra `-`

**Comment by ahegyes** [comment]
👋 @smaffulli! This has been addressed on the staging site via PR #48.

Before:
![image](https://github.com/OpenSourceOrg/dotOrg/assets/36231502/1ef093c7-bb41-42a3-8155-ed1e08dc03ab)

After:
![image](https://github.com/OpenSourceOrg/dotOrg/assets/36231502/b76cffb6-c982-4a8e-b4a6-487c4baeb273)

If this is as you expected, we can deploy this live by merging PR #49. Thank you!

**Comment by nickvidal** [comment]
Yes, that would be great. Thank you!

**Comment by ahegyes** [comment]
This has been merged 😄 https://opensource.org/events/open-source-ai-definition-town-hall-4/ 

![image](https://github.com/OpenSourceOrg/dotOrg/assets/36231502/8075ee4d-3858-4ac1-ad5f-6264ad344f42)
