### ISSUE TITLE
SugarCalendar - List of events shown in random order

### ISSUE THREAD

**Issue by smaffulli** [OpenSourceOrg/dotOrg#37]
### Description

When I go to https://opensource.org/events/ the list is shown in an order that doesn't seem to be useful. The list should show the upcoming events by default.

**Comment by ajolo2ky** [comment]
Ordered by the most immediate one first (the one on January 12th should be the first one displayed)

**Comment by ahegyes** [comment]
Upcoming events are now the default when visiting the `/events` page. The top-most event will be the one immediately upcoming (current on Feb 9th) and the lower on the page on is, the further out the events are. Closing this issue but feel free to reopen if something needs tweaked. 

https://opensource.org/events/

**Comment by nickvidal** [comment]
Much better, thank you!
