### ISSUE TITLE
Link stopped working: http://www.opensource.org/licenses/bsd-license.php

### ISSUE THREAD

**Issue by DmitryFromDubna** [OpenSourceOrg/dotOrg#4]
Hello, http://www.opensource.org/licenses/bsd-license.php worked [previously](https://web.archive.org/web/20230101004808/https://opensource.org/licenses/bsd-license.php), but does not work now. It is referenced by https://repo1.maven.org/maven2/com/sun/media/jai_imageio/1.1/jai_imageio-1.1.pom , that's why we use that link in our documentation.

Are you going to restore or drop this link? Thank you.

**Comment by smaffulli** [comment]
Thanks for providing the link to the Archive. I double-checked also on the old site and indeed, that link points to the BSD-2-Clause license. The better link should be this one https://opensource.org/license/bsd-2-clause/
I setup a 301 redirect
