### ISSUE TITLE
Calendar pages broken on mobile

### ISSUE THREAD

**Issue by ajolo2ky** [OpenSourceOrg/dotOrg#40]
### Description

The calendar pages are broken when browsing on mobile

### Steps to reproduce

On mobile go to https://opensource.org/events/open-source-ai-definition-town-hall/

### What you expected to happen

Page is displayed responsively

### What actually happened

![image](https://github.com/OpenSourceOrg/dotOrg/assets/6595356/4449fe9c-e2a7-4d5c-9669-8409eb2c294a)

**Comment by ajolo2ky** [comment]
Reproduced on Firefox and Chrome on iOS

**Comment by ahegyes** [comment]
Hi @ajolo2ky! We've tweaked the mobile view in PR #46 that was merged on the staging site.

Before:
![image](https://github.com/OpenSourceOrg/dotOrg/assets/36231502/19fdaba8-4185-4c73-8b07-5252a59022a5)

After:
![image](https://github.com/OpenSourceOrg/dotOrg/assets/36231502/3ea1d1aa-4d0f-4338-9a45-04b080d9de2a)

Let us know if we should deploy these changes live! Thank you!

**Comment by nickvidal** [comment]
They look the same to me :)

**Comment by ahegyes** [comment]
The text is no longer overflowing the screen and some paddings have been adjusted. Did you have something else in mind, like maybe more margins between the individual elements?

**Comment by nickvidal** [comment]
I now see it. I got confused because it seems like there's hidden text in the header.
I think that's fine, thanks @ahegyes!

**Comment by ahegyes** [comment]
> I got confused because it seems like there's hidden text in the header.

That is being looked at in #35 😄 We've deployed the changes here in #47

**Comment by nickvidal** [comment]
Thanks!
