### ISSUE TITLE
OpenSource.org | Replace columned layout with a gallery

### ISSUE THREAD

**Issue by toncijajic** [OpenSourceOrg/dotOrg#5]
OpenSource would like to replace the current column-based system of managing and adding sponsor logos on https://opensource.org/sponsors with something easier to manage.

We've suggested a gallery instead, making their life a bit easier.

I've added an initial exploration of the idea to [this copy post](https://opensource.org/wp-admin/post.php?post=6678&action=edit), using a regular Gutenberg gallery block, and would like to add a few more features to make it more usable:

- Linking from an image to the sponsor's site (we can use a caption or description filed for this)
- Images not spreading over more than 1 column (added as a togglable option)
- Ideally, a "Sort Alphabetically" option in the Edit Gallery screen that uses the Image Title

[Zendesk reference](https://woothemes.zendesk.com/agent/tickets/6286485)

**Comment by nickvidal** [comment]
Hi @toncijajic, looks good to me with your suggestions. Thanks!

**Comment by ecairol** [comment]
@toncijajic  I'm posting a follow-up question here. Here's the whole conversation for better context:

> [ecairol](https://github.com/ecairol) commented [16 hours ago](https://github.com/a8cteam51/team51-dev-requests/issues/2646#issuecomment-1590074441)
> @toncijajic This is in a good spot now, the first two blocks, Innovator and Premiere, have been updated in the Test Page and now they use the new WP block: https://opensource.org/?page_id=6678
> Please check it out and let me know all the feedback you might have.


> [toncijajic](https://github.com/toncijajic) commented [1 hour ago](https://github.com/a8cteam51/team51-dev-requests/issues/2646#issuecomment-1591208790)
Hey @ecairol, thanks for the update!
> Looking at it, both are currently in a single column; it this a bug?
> Re-reading my original task, this might be a confusing thing:
> Images not spreading over more than 1 column (added as a togglable option)
> What I meant by that is that it needs to look like option 2 from this screenshot.

Thanks for clarifying, I definitely misunderstood that part but this should be an easy fix with CSS.

My only question is, should the small logos still display next to each other in 3 columns, or should they always stack one on top of the other?

Still pending to add the toggle option but I'll do that today.

**Comment by smaffulli** [comment]
i think we need a bit more options with the number of columns because we need to show different logo sizes for different sponsorship levels.

I also noticed that changing the number of columns doesn't affect the size of the logos... 

This doesn't seem to go in the right direction... How about we simply use the default Gallery block? or other image galleries that already exist?

**Comment by smaffulli** [comment]
I thought this was ready for review, that's why I jumped in. My mistake. Keep going :)

**Comment by toncijajic** [comment]
@ecairol confirming [the clone page](https://opensource.org/?page_id=6678&preview=true) looks and feels like https://opensource.org/sponsors currently does. I've informed OpenSource about this and suggested we move the Sponsors page to use your custom solution.

Additionally, we should explore changing the mobile breakpoint behavior from the current "break into a single column" behavior we copied from the Sponsors page into something more intuitive.

I was thinking about something like:

`Reduce column/image width until you hit 75-80% original width, then rearrange the gallery to one column less. Rinse and repeat until 1 column.`

This would make the steps look nicer.

**Comment by securityjedi** [comment]
Hi @ecairol,

Just tagging you here in case you missed Tonći's earlier comment. =)

**Comment by ecairol** [comment]
Sure thing! Thanks, @securityjedi.

> I've informed OpenSource about this and suggested we move the Sponsors page to use your custom solution.

I'd like confirmation that we are indeed going with this solution live, along with the idea of re-arranging the gallery dynamically based on window width (not a current behavior on the existing site, so I was under the impression we needed confirmation)

**Comment by nickvidal** [comment]
It looks great to me, thank you! I'll double check with @smaffulli. He's travelling, but should get back to you soon.

**Comment by ecairol** [comment]
This is all set on the [test page](https://opensource.org/wp-admin/post.php?post=6678&action=edit).
Next Monday I'll change the current slug of the test page to be `/sponsors`, and the current Sponsors page will be make Private and changed to `/sponsors-old`

**Comment by ecairol** [comment]
@toncijajic sorry for the delay last week. The page update is now in place.

**Comment by toncijajic** [comment]
@ecairol, this feels neat to use across viewpoint widths; thank you!

Closing this as complete. ✅
