### ISSUE TITLE
`Source` spelled `Spurce` in alt text for `osi-badge-light.svg` on license pages

### ISSUE THREAD

**Issue by alexquick** [OpenSourceOrg/dotOrg#6]
It looks like there's a misspelling in the alt text on the license page template. Unfortunately it's the one that Google is selecting as the result summary. Anyway `s/Spurce/Source/g`.

Example: https://opensource.org/license/bsd-1-clause/ (though all licenses seem affected).
```
. . . snip . . .
<img width="200" src="/wp-content/themes/osi/assets/img/osi-badge-light.svg" alt="Open Spurce Initiative Approved License">
```

Thanks for making such a great resource!

**Comment by smaffulli** [comment]
This has been fixed and is in production.
