### ISSUE TITLE
Licences path change intentional?

### ISSUE THREAD

**Issue by nvollmar** [OpenSourceOrg/dotOrg#60]
Our link checker broke due to the sudden change of `https://opensource.org/licenses/BSD-3-Clause` to `https://opensource.org/blog/license/bsd-3-clause`.

Is this change intentional and will stay that way?

**Comment by smaffulli** [comment]
Not intentional, we're fixing it... The patch should merge momentarily

**Comment by nvollmar** [comment]
Just rechecked the new link, there is still a difference (licenses vs license):
old:  https://opensource.org/licenses/BSD-3-Clause
new: https://opensource.org/license/bsd-3-clause

**Comment by smaffulli** [comment]
Are you sure that's the right old URL? I see in the archive last month the
url was /license/ without the s
https://web.archive.org/web/20240121031557/https://opensource.org/license/bsd-3-clause/

**Comment by raboof** [comment]
hmm, for example both https://spdx.org/licenses/BSD-3-Clause.html and https://en.wikipedia.org/wiki/BSD_licenses link to 'licenses' - perhaps it used to be a redirect?

**Comment by nvollmar** [comment]
In all our dependencies, all references are to /licenses. Couldn't find anything linking to /license

**Comment by smaffulli** [comment]
the overall redirect from licenses/ to license/ should be fixed now

**Comment by nvollmar** [comment]
thank you, I can confirm that our issue is fixed 👍🏻
