### ISSUE TITLE
Site Search not returning any result

### ISSUE THREAD

**Issue by moyvincent** [OpenSourceOrg/dotOrg#70]
### Description

When using the search icon on the site: http://opensource.org/, it redirects to https://opensource.org/?s=Nerdearla which doesn't display any results.

When using the URL https://opensource.org/blog/?s=Nerdearla, it displays a result

```
<form role="search" method="get" class="search-form" action="https://opensource.org/">
	<label>
		<span class="screen-reader-text">Search for:</span>
			<input type="search" class="search-field" placeholder="Search …" value="" name="s">
	</label>
		<input type="submit" class="search-submit" value="Search">
</form>
```
Doing a browser inspect, I saw the form with the action to be the URL: https://opensource.org/.
Maybe we could adjust this to include the blog URL as well: https://opensource.org/blog/

### Steps to reproduce

1. Visit http://opensource.org/ and click on the Search Icon on the header section
2. Enter "Nerdearla" as the word to search for 
3. Notice no result is found and the URL shows https://opensource.org/?s=Nerdearla
4. When you visit the URL https://opensource.org/blog/?s=Nerdearla instead, you see a result

### What you expected to happen

The Search should return results since this is a site-wide search

### What actually happened

The search doesn't return any results only when visiting https://opensource.org/blog/?s=Nerdearla.

### Reference
[Zendesk](https://a8c.zendesk.com/agent/tickets/7988984)
[Dev Repo](https://github.com/a8cteam51/team51-dev-requests/issues/3963)

**Comment by wpspecialprojects** [comment]
This was a configuration issue in the [Relevanssi plugin](https://wordpress.org/plugins/relevanssi/). Resolved.
