### ISSUE TITLE
Update the Search Results Page

### ISSUE THREAD

**Issue by jonesch** [OpenSourceOrg/dotOrg#77]
### Description

We'd like to update the Search results page to better showcase pages, posts, and other content while continuing to use the Table format that works rather well for the `licenses`.

Given that we're aiming to have two different layouts/formats on the Search Results page, one for License Post Type and one for everything else, I think we have two options.

The Search results will default to 10 items; I suggest we change that query to pull 20.

### Option 1
We can NOT have any pagination, but just display 10 Posts/Pages, and then display 10 of the License post type. I put together that mockup here:
![opensource org_s=ethical-practice](https://github.com/OpenSourceOrg/dotOrg/assets/1905918/570bb16f-301f-4a4f-963a-32446e13fd3b)

### Option 2
Would have the same layout as Option 1, but we could could pagination. On the search results, we'd loop through the 20 results and return Posts/Pages to one Bucket. And then Licesns to another bucket. And then display them in the same layout as Option 1. But the results/buckets might be uneven - Page 1 of Search Results could be 17 Posts/Pages and 3 Licenses. Then on Page 2, it could be 16 Licenses and 4 Posts/Pages. The layout/results might be uneven, but it would allow us to keep pagination and loop through the Search by 20 items at a time and display each in their appropriate section.

**Comment by ajolo2ky** [comment]
Hi, thanks for putting this together! I think Option 2 makes more sense in the interest of the user who is trying to search for something. Let's move forward with that.

**Comment by jonesch** [comment]
Howdy @ajolo2ky and @smaffulli -

Jetpack offers a Search tool that we could also try out. We spun up a new development site to test it and made small adjustments to match the styling. You can preview it here: https://open-source-initiative-jetpacksearch.mystagingwebsite.com/?s=What%20is%20Open%20Source

To @smaffulli's point above: `search be faceted by post type?`, it addresses that by allowing folks to filter their Search Results based on those post types, by years, and/or categories.

Have a look and let us know what you think of this as an option!

**Comment by smaffulli** [comment]
that's what we need *but* not with Jetpack! We don't want to manage cookies, we have a strict requirement not to *ever* require a cookie banner on our sites. Those banners are just awful.

Is there a search plugin that doesn't require a cookiebanner?

**Comment by jonesch** [comment]
We have [Jetpack](https://jetpack.com) installed on the production site and this staging site (_where we have Jetpack Search active_). Knowing your cookie policy, Jetpack does not load cookies on a user's device, so there is no need for a Cookie Banner. The Complianz plugin installed on the site offers the ability to block plugins from loading cookies, and Jetpack is already on that block list.

While [Jetpack does use and occasionally requires Cookies for certain features](https://jetpack.com/support/cookies/), they are not needed to use Jetpack Search. Jetpack Search tries to load a Cookie with an anonymous ID for usage stats, but Complianz is blocking that for you.

If you use Jetpack Search, **no new cookies will be added**. Your site will still have zero cookies loading for any visitors.

**Comment by smaffulli** [comment]
Ok, I based my comment on the scan I ran on the staging site that showed  6
performance cookies being loaded by the search page. If no cookies are
added, go ahead and use Jetpack search then. Thanks

**Comment by jonesch** [comment]
@bernattorras - we are wanting to add Jetpack Search to the site and we've done that work over on:
https://open-source-initiative-jetpacksearch.mystagingwebsite.com/

I don't have Write Permissions to this Repo, so can you update Lines 51-53 on the following file to the below code:
https://github.com/OpenSourceOrg/dotOrg/blob/main/themes/osi/header.php#L51C1-L53
```
<a aria-label="Open Search" class="open-search open-button jetpack-search-filter__link" href="#">
	<?php OSI\SVG::the_svg( 'search' ); ?>
</a>
```

And also remove line 65 on:
https://github.com/OpenSourceOrg/dotOrg/blob/main/themes/osi/header.php#L65

Can you push this on both `develop` and `main`?

**Comment by bernattorras** [comment]
@jonesch I've applied these changes to both the development and production sites and configured the Jetpack Search filters in the Search sidebar as in the development site. 

Let me know if anything else is needed!

**Comment by jonesch** [comment]
Thank you, @bernattorras! I added a snippet of CSS in the Customizer to extend the Input form on the search bar 100%.

cc: @smaffulli and @ajolo2ky here as the Search is now live!

Closing this GH Issue out. ❤️
