### ISSUE TITLE
OpenSource.org | Add last modified on certain pages

### ISSUE THREAD

**Issue by toncijajic** [OpenSourceOrg/dotOrg#9]
To make the visitors aware that some content might not be relevant anymore, we need to add the "Last modified on" to the bottom of page templates.

## Scope

We need to add a "Last modified on [date]" (using `the_modified_time('F jS, Y');`?) to the bottom of the page template.
We also need to add "Page created on" to the bottom of the page template.

`Page created on 21 July 2019 | Last modified on 19 June 2021`

### Details

- Only add to the pages created before February 2023
- Use full date format, expanded form (21 August 2023)
- Do note include this on the homepage

**Comment by webmink** [comment]
I am concerned that "touches" to pages may make them look current. In general, the date of publication is probably a better indication of relevance than the last modified date (see for example opensource.org/osr). Is it feasible to add both in the case that they differ?  I have previously included it as text in the page where it is highly significant.

**Comment by toncijajic** [comment]
> Is it feasible to add both in the case that they differ? I have previously included it as text in the page where it is highly significant.

@webmink good point!
Any recommendation on conditional addition in that case - last modified over a year ago OR created over three years ago?

cc @smaffulli for visibility

**Comment by toncijajic** [comment]
> If all pages before Feb 2023 show a "Page created on" and also show "Last modified on" I think it'd work, until we can review the whole site.

@smaffulli good idea, works for us!

**Comment by bernattorras** [comment]
@toncijajic I've pushed these changes into the [staging site](https://open-source-initiative-development.mystagingwebsite.com/about/) to confirm if they are being displayed as expected.

#### Notes / Considerations
- This feature has been applied to the default page template and the No Page Header template as this last template was also used for the following pages:
    - [Home Page](https://opensource.org/wp-admin/post.php?post=2&action=edit)
    - [About old](https://opensource.org/wp-admin/post.php?post=157&action=edit)
    - [About](https://opensource.org/wp-admin/post.php?post=335&action=edit)
    - [Programs](https://opensource.org/wp-admin/post.php?post=5052&action=edit)
    - [Home Page - License clinic](https://opensource.org/wp-admin/post.php?post=5245&action=edit)
    - [Legal Program](https://opensource.org/wp-admin/post.php?post=5425&action=edit)
    - [ClearlyDefined](https://opensource.org/wp-admin/post.php?post=5308&action=edit)
    - [Policy and standards program](https://opensource.org/wp-admin/post.php?post=5446&action=edit)
    - [Home Page - standard](https://opensource.org/wp-admin/post.php?post=5665&action=edit)
    - [Practical Open Source](https://opensource.org/wp-admin/post.php?post=6073&action=edit)
    - [Deep Dive](https://opensource.org/wp-admin/post.php?post=6498&action=edit)
    - [The Open Policy Alliance](https://opensource.org/wp-admin/post.php?post=7914&action=edit)
    - [Home Page - DDAI](https://opensource.org/wp-admin/post.php?post=7114&action=edit)
- The Home (and Front) page are always excluded by a conditional
- Perhaps we could consider adding this information below the title instead of at the bottom of the page? Sometimes it is good for the user to know this information before reading the full article (especially if the content could be outdated or non-relevant anymore)

**Comment by smaffulli** [comment]
thanks. I like the idea of moving showing the age of the page below the title, for older pages.

**Comment by smaffulli** [comment]
Looks good, thanks!

**Comment by toncijajic** [comment]
@bernattorras looks good! Feel free to push to production and let me know. 🙌

**Comment by bernattorras** [comment]
@toncijajic Done! Feel free to reopen the issue if something else is needed!
